#!/bin/bash

CURRENT_DIR="$(pwd)"

grep -r -l -E 'Mail delivery failed: returning message to sender|Mail delivery deferred: returning message to sender|Mail failure|Message Delivery Failure|Undeliverable:|Undelivered Mail' "$CURRENT_DIR" | tee /tmp/mail_delete_list.txt | wc -l
